apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workspace-gateway
  labels:
    app: workspace-gateway
rules:
- apiGroups:
  - workspace.devplane.io
  resources:
  - workspaces
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - workspace.devplane.io
  resources:
  - workspaces/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workspace-gateway
  labels:
    app: workspace-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workspace-gateway
subjects:
- kind: ServiceAccount
  name: workspace-gateway
  namespace: workspace-operator-system
