apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader-election-rolebinding
  namespace: workspace-operator-system
  labels:
    app.kubernetes.io/name: workspace-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: controller-manager
  namespace: workspace-operator-system
