apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manager-rolebinding
  labels:
    app.kubernetes.io/name: workspace-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: controller-manager
  namespace: workspace-operator-system
