{{- if and .Values.gateway.enabled .Values.gateway.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "workspace-operator.labels" . | nindent 4 }}
spec:
  {{- if .Values.gateway.ingress.className }}
  ingressClassName: {{ .Values.gateway.ingress.className | quote }}
  {{- end }}
  rules:
  - host: {{ .Values.gateway.ingress.host | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-gateway
            port:
              name: http
  {{- if .Values.gateway.ingress.tls }}
  tls:
    {{- toYaml .Values.gateway.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}
