{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "workspace-operator.labels" . | nindent 4 }}
    app: workspace-gateway
{{- end }}
