apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "workspace-operator.labels" . | nindent 4 }}
